import turtle as t


def square(x, y, side):
    t.pencolor('#800000')
    t.pu()
    t.pensize(5)
    t.speed(10)
    t.goto(x, y)
    t.pd()
    for i in range(4):
        t.fd(side)
        t.rt(90)
    t.rt(45)
    t.fd((2*side**2)**0.5)
    t.rt(135)
    t.fd(side)
    t.rt(135)
    t.fd((2*side**2)**0.5)
    t.rt(45)
    t.setheading(0)
    t.pu()


def triangle_right(x, y, side, color):
    t.pencolor(color)
    t.pensize(5)
    t.speed(10)
    t.goto(x, y)
    t.pd()
    t.fillcolor(color)
    t.begin_fill()
    t.rt(30)
    t.fd(side)
    t.rt(120)
    t.fd(side)
    t.end_fill()
    t.rt(180)
    t.fd(side)
    t.setheading(0)
    t.pu()


def triangle_left(x, y, side, color):
    t.pencolor(color)
    t.pencolor(color)
    t.pensize(5)
    t.speed(10)
    t.goto(x, y)
    t.pd()
    t.fillcolor(color)
    t.begin_fill()
    t.lt(30)
    t.fd(side)
    t.rt(120)
    t.fd(side)
    t.rt(120)
    t.fd(side)
    t.rt(180)
    t.fd(side)
    t.end_fill()
    t.setheading(0)
    t.lt(90)
    t.fd(side)
    t.rt(90)
    t.setheading(0)
    t.pu()


def circle(x, y, radius, color):
    t.pencolor(color)
    t.goto(x, y)
    t.pensize(5)
    t.speed(10)
    t.pd()
    t.fillcolor(color)
    t.begin_fill()
    t.circle(radius)
    t.end_fill()
    t.pu()
    t.setheading(0)


square(-200, 0, 100)
triangle_right(-100, 0, 100, '#CD5C5C')
circle(40, -100, 50, '#B22222')
triangle_left(95, -50, 100, '#CD5C5C')
square(185, 0, 100)
triangle_right(285, 0, 100, '#CD5C5C')
circle(425, -100, 50, '#B22222')
triangle_left(475, -50, 100, '#CD5C5C')
square(565, 0, 100)
t.mainloop()
